import{S as h,i as l,a as g}from"./assets/vendor-eacb4d5c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const u=document.querySelector(".search-img-form"),m=document.querySelector(".gallery"),d=document.querySelector(".loader"),a=document.querySelector(".load-more-btn"),y=new h(".gallery a",{captionsData:"alt",captionDelay:250});u.addEventListener("submit",v);function L(i,t){return g.create({baseURL:"https://pixabay.com/api/",params:{key:"41836139-8e3290e3b09a716b148135a6e",image_type:"photo",orientation:"horizontal",safesearch:!0,q:i,page:t,per_page:40}}).get()}async function b(i,t){try{const s=await L(i,t);return s.data.totalHits===0&&(l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a.classList.add("is-hidden")),s.data}catch(s){console.log(s)}}let n=!1;function v(i){i.preventDefault(),m.innerHTML="";const t=i.currentTarget.elements.search.value;a.classList.add("is-hidden");let s=1;if(n&&(a.removeEventListener("click",n),n=!1),t===""||t===void 0){l.error({message:"Please, fill in the search field",position:"topRight"});return}n=async()=>{try{d.classList.remove("is-hidden");const r=await b(t,s++);return d.classList.add("is-hidden"),r.totalHits>0&&(w(r.hits),y.refresh()),s>1&&r.totalHits>0&&a.classList.remove("is-hidden"),r}catch(r){console.log(r)}},n(),u.reset(),a.addEventListener("click",async()=>{a.classList.add("is-hidden");const r=await n(),e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"}),s>Math.ceil(r.totalHits/40)&&(setTimeout(()=>{l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})},1e3),a.classList.add("is-hidden"))})}function w(i){const t=i.map(({webformatURL:s,largeImageURL:r,tags:e,likes:o,views:c,comments:f,downloads:p})=>`<li class="gallery-item">
          <a class="gallery-link" href="${r}">
            <img class="gallery-image" src="${s}" alt="${e}" />
            <div class="image-info">
              <p class="likes">Likes ${o}</p>
              <p class="views">Views ${c}</p>
              <p class="comments">Comments ${f}</p>
              <p class="downloas">Downloas ${p}</p>
            </div>
          </a>
        </li>`).join("");m.insertAdjacentHTML("beforeend",t)}
//# sourceMappingURL=commonHelpers.js.map
