import{S as h,i as d,a as y}from"./assets/vendor-eacb4d5c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m=document.querySelector(".search-img-form"),p=document.querySelector(".gallery"),u=document.querySelector(".loader"),n=document.querySelector(".load-more-btn"),L=new h(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",w);n.addEventListener("click",q);function b(o,t){return y.create({baseURL:"https://pixabay.com/api/",params:{key:"41836139-8e3290e3b09a716b148135a6e",image_type:"photo",orientation:"horizontal",safesearch:!0,q:o,page:t,per_page:40}}).get()}async function v(o,t){try{const s=await b(o,t);return s.data.totalHits===0?(n.classList.add("is-hidden"),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})):s.data}catch(s){console.log(s)}}let l=null,i=1;function w(o){o.preventDefault(),p.innerHTML="";const t=o.currentTarget.elements.search.value;if(n.classList.add("is-hidden"),i=1,t===""||t===void 0){d.error({message:"Please, fill in the search field",position:"topRight"});return}return l=async()=>{try{u.classList.remove("is-hidden");const s=await v(t,i);return i+=1,u.classList.add("is-hidden"),S(s.hits),L.refresh(),i>1&&s.totalHits>40&&n.classList.remove("is-hidden"),s}catch(s){console.log(s)}},l(),m.reset(),i}async function q(){const o=await l();console.log(i),console.log(Math.ceil(o.totalHits/40));const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"}),i>Math.ceil(o.totalHits/40)&&(d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.classList.add("is-hidden"))}function S(o){const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:a,comments:f,downloads:g})=>`<li class="gallery-item">
          <a class="gallery-link" href="${c}">
            <img class="gallery-image" src="${s}" alt="${e}" />
            <div class="image-info">
              <p class="likes">Likes ${r}</p>
              <p class="views">Views ${a}</p>
              <p class="comments">Comments ${f}</p>
              <p class="downloas">Downloas ${g}</p>
            </div>
          </a>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t)}
//# sourceMappingURL=commonHelpers.js.map
